# Find more information about the configuration file here:
# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=python

runtime: python39
entrypoint: gunicorn -b :$PORT app:app

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

automatic_scaling:
  target_cpu_utilization: .75
  min_instances: 1
